# TODO: install from requirements.txt

tasks:
  - name: Dependencies & Database
    init: |
      python3 -m venv .venv
      source .venv/bin/activate
      pip install -U pyright git+https://github.com/RobertCraigie/prisma-client-py#egg=prisma-client[aiohttp]
      prisma db push
