# TODO: install from requirements.txt

tasks:
  - name: Dependencies & Database
    init: |
      pip install -U pyright git+https://github.com/RobertCraigie/prisma-client-py#egg=prisma-client[aiohttp]
      prisma db push
